### ISSUE TITLE
Use class to hide and show instead of .hide() and .show()

### ISSUE THREAD

**Issue by rajzshkr** [chieakiba/quiz-app#5]
https://github.com/chieakiba/quiz-app/blob/master/js/app.js#L47

Reference - https://twitter.com/paul_irish/status/564443848613847040

**Sample**
```css
.hide{
  display: none;
}
```
```javascript
$(selector).addClass('hide');
```
